from pathlib import Path

# Shared cross-assistant changelog.
path = Path('AI_CHANGELOG.md')
text = path.read_text(encoding='utf-8')
marker = '## Unreleased\n'
heading = '### ChatGPT — 2026-09-14 — live grip-closure tuning and collision baseline'
entry = f'''\n{heading}\n\nAdded a live **Grip closure** control to the Exercise panel so the repaired imported character can be tuned through the exact deterministic production generator instead of recompiling guessed closure values. `StudioState.setGripClosure` clamps to 0..1, copies the exercise hand spec, regenerates the clip through `generateClip`, participates in normal undo/redo history, and leaves the authored dumbbell-curl default at **0.85**. The panel exposes a 0–100% range in 5% steps with an exact percentage readout. No exercise default, rig, imported-character mapping, equipment socket, candidate GLB, skin weights or retargeting rule was changed by this tooling pass.\n\nAdded `src/editor/store.test.ts` regression coverage for deterministic bilateral finger regeneration, clamping and undo back to the authored 85% value. Full validation before the feature commit was pushed: `npm run typecheck` passed; `npm test` passed **200 tests with 1 optional real-character diagnostic skipped** across 18 test files; `npm run build` passed with only the existing >500 kB Vite chunk advisory. The validated feature commit is `e2ebca5` (`feat: add live grip closure tuning`).\n\nAlso quantified the remaining small dumbbell/skin intersections using the saved production-posed repaired-hand evidence and the Studio's 15 mm-radius / 120 mm handle. The later v5 elbow and shoulder passes did not change hand geometry, grip calibration, closure or equipment attachment, so this is a useful baseline but **not a substitute for a fresh live v5 render**. At the authored 85% closure the strict cylinder test finds 103 hand/finger surface vertices per hand inside the handle, bilaterally symmetric and repeated in shoulder press: thumb 28 (max 13.18 mm), index 8 (6.91 mm), middle 3 (3.62 mm), ring 9 (8.90 mm), pinky 25 (12.53 mm), hand/palm 30 (14.57 mm). The concentration in palm/thumb/pinky means a whole-dumbbell translation is a poor first fix; it can help one side while worsening the other. A separate attempt to approximate lower closure by directly rotating source Rigify fingers was rejected because absolute anatomical retargeting made that approximation miss production digit positions by roughly 15–29 mm depending on reconstruction. Do not use that approximation to choose a permanent value.\n\nTomorrow review: load the proven v5 candidate and the separate `OUTER_ELBOW` review candidate, keep the curl at 85% first, then use the new live control to compare 80/75/70/65% at curl bottom/mid/top and shoulder-press start. Judge handle penetration, full finger enclosure, thumb placement, palm loading, equipment centring/rigidity and left/right symmetry. Only change the authored 85% value if the live imported-character A/B clearly improves the grip without making it look loose. The Library folder `/HomeGymPT Animation Review 2026-09-14` now also contains `Grip-Intersection-Diagnostic.md/.csv` plus the elbow candidate/evidence and curl motion profile.\n'''
if heading not in text:
    if marker not in text:
        raise SystemExit('Unreleased marker not found')
    path.write_text(text.replace(marker, marker + entry + '\n', 1), encoding='utf-8')

# Keep the candidate repair doc useful as a single tomorrow-review checklist.
path = Path('docs/CHARACTER_CANDIDATE_REPAIR.md')
text = path.read_text(encoding='utf-8')
heading2 = '## Live grip review tooling'
append = '''\n\n## Live grip review tooling\n\nThe Studio now exposes the exercise's **Grip closure** in the Exercise panel. It is a normal undoable exercise edit and regenerates through the production clip generator; the authored curl default remains 85%. Use this instead of editing finger bones or source-rig rotations by hand when reviewing the remaining handle/skin intersections.\n\nBaseline production evidence at 85% finds 103 surface vertices per hand inside the 15 mm-radius dumbbell handle, concentrated in hand/palm (30), thumb (28) and pinky (25), with far less overlap at the middle finger (3). This pattern repeats in the shoulder press, so do not move the whole dumbbell as the first response. Tomorrow, visually compare 85/80/75/70/65% using the actual imported candidate and keep the lowest-overlap value only if all digits still form a secure, natural wrap and the thumb/palm remain convincing. These saved collision counts are a diagnostic baseline, not live-v5 visual certification.\n'''
if heading2 not in text:
    path.write_text(text.rstrip() + append + '\n', encoding='utf-8')
