import type { BoneName, Finger, Side } from './boneNames';
import { FINGERS, SIDES } from './boneNames';
import type { AxisLimit, BoneDefinition, JointLimits, Vec3 } from './types';
import { vec3 } from './types';

/**
 * The canonical humanoid rig: roughly a 1.75 m adult, standing on the floor at
 * the origin, facing +Z. The character's left is world -X (the side you see on
 * the right of the screen from the default front camera).
 *
 * The arms hang vertically at rest so that a shoulder abduction angle means
 * exactly what it says — a rig with built-in splay quietly adds a few degrees
 * to every angle an exercise author writes down.
 *
 * Rest positions are authored in world space because that is how a body is
 * actually measured; the bone-local frames and parent-relative offsets are
 * derived from them in `skeleton.ts`.
 */

const limit = (min: number, max: number, positive: string, negative: string): AxisLimit => ({
  min,
  max,
  positive,
  negative,
});

const joint = (
  x: AxisLimit | null,
  y: AxisLimit | null,
  z: AxisLimit | null,
): JointLimits => ({ x, y, z });

/** Free joint, used for the root and as a permissive default. */
const free = (): JointLimits =>
  joint(
    limit(-180, 180, 'Pitch up', 'Pitch down'),
    limit(-180, 180, 'Yaw left', 'Yaw right'),
    limit(-180, 180, 'Roll right', 'Roll left'),
  );

/** Mirror a single axis limit for the opposite side of the body. */
function mirrorLimit(axis: AxisLimit | null): AxisLimit | null {
  if (!axis) return null;
  return { min: -axis.max, max: -axis.min, positive: axis.negative, negative: axis.positive };
}

/**
 * Flexion (x) has the same sign on both sides of the body; axial rotation (y)
 * and abduction (z) are handed, so they flip.
 */
function mirrorLimits(limits: JointLimits): JointLimits {
  return { x: limits.x, y: mirrorLimit(limits.y), z: mirrorLimit(limits.z) };
}

const mirrorVec = (v: Vec3): Vec3 => vec3(-v.x, v.y, v.z);

/** Produce the right-side twin of a left-side bone definition. */
function mirrorBone(bone: BoneDefinition): BoneDefinition {
  const swap = (name: BoneName | null): BoneName | null =>
    name && name.endsWith('_l') ? (`${name.slice(0, -2)}_r` as BoneName) : name;
  return {
    ...bone,
    name: swap(bone.name) as BoneName,
    parent: swap(bone.parent),
    head: mirrorVec(bone.head),
    tail: mirrorVec(bone.tail),
    limits: mirrorLimits(bone.limits),
  };
}

// ---------------------------------------------------------------------------
// Spine, head and root
// ---------------------------------------------------------------------------

const CENTRE_BONES: BoneDefinition[] = [
  {
    name: 'root',
    parent: null,
    head: vec3(0, 0, 0),
    tail: vec3(0, 0.2, 0),
    limits: free(),
    radius: 0.05,
  },
  {
    name: 'pelvis',
    parent: 'root',
    head: vec3(0, 0.95, 0),
    tail: vec3(0, 1.03, 0),
    limits: joint(
      limit(-45, 45, 'Anterior tilt', 'Posterior tilt'),
      limit(-45, 45, 'Rotation right', 'Rotation left'),
      limit(-30, 30, 'Hike left', 'Hike right'),
    ),
    radius: 0.115,
  },
  {
    name: 'spine_01',
    parent: 'pelvis',
    head: vec3(0, 1.03, 0),
    tail: vec3(0, 1.15, 0),
    limits: joint(
      limit(-15, 30, 'Flexion', 'Extension'),
      limit(-12, 12, 'Rotation right', 'Rotation left'),
      limit(-22, 22, 'Side bend left', 'Side bend right'),
    ),
    radius: 0.105,
  },
  {
    name: 'spine_02',
    parent: 'spine_01',
    head: vec3(0, 1.15, 0),
    tail: vec3(0, 1.27, 0),
    limits: joint(
      limit(-12, 25, 'Flexion', 'Extension'),
      limit(-20, 20, 'Rotation right', 'Rotation left'),
      limit(-20, 20, 'Side bend left', 'Side bend right'),
    ),
    radius: 0.11,
  },
  {
    name: 'spine_03',
    parent: 'spine_02',
    head: vec3(0, 1.27, 0),
    tail: vec3(0, 1.42, 0),
    limits: joint(
      limit(-10, 20, 'Flexion', 'Extension'),
      limit(-25, 25, 'Rotation right', 'Rotation left'),
      limit(-18, 18, 'Side bend left', 'Side bend right'),
    ),
    radius: 0.125,
  },
  {
    name: 'neck',
    parent: 'spine_03',
    head: vec3(0, 1.42, 0),
    tail: vec3(0, 1.52, 0),
    limits: joint(
      limit(-45, 40, 'Flexion', 'Extension'),
      limit(-55, 55, 'Rotation right', 'Rotation left'),
      limit(-35, 35, 'Side bend left', 'Side bend right'),
    ),
    radius: 0.055,
  },
  {
    name: 'head',
    parent: 'neck',
    head: vec3(0, 1.52, 0),
    tail: vec3(0, 1.75, 0),
    limits: joint(
      limit(-20, 20, 'Flexion', 'Extension'),
      limit(-25, 25, 'Rotation right', 'Rotation left'),
      limit(-15, 15, 'Side bend left', 'Side bend right'),
    ),
    radius: 0.095,
  },
];

// ---------------------------------------------------------------------------
// Left arm and leg — the right side is generated by mirroring
// ---------------------------------------------------------------------------

const LEFT_BONES: BoneDefinition[] = [
  {
    name: 'clavicle_l',
    parent: 'spine_03',
    head: vec3(-0.02, 1.42, 0.012),
    tail: vec3(-0.17, 1.44, 0),
    limits: joint(
      limit(-18, 18, 'Protraction', 'Retraction'),
      null,
      limit(-25, 10, 'Depression', 'Elevation'),
    ),
    radius: 0.035,
  },
  {
    name: 'upperarm_l',
    parent: 'clavicle_l',
    head: vec3(-0.17, 1.44, 0),
    tail: vec3(-0.17, 1.14, 0),
    limits: joint(
      limit(-60, 180, 'Flexion', 'Extension'),
      limit(-90, 90, 'External rotation', 'Internal rotation'),
      limit(-180, 40, 'Adduction', 'Abduction'),
    ),
    radius: 0.05,
  },
  {
    name: 'forearm_l',
    parent: 'upperarm_l',
    head: vec3(-0.17, 1.14, 0),
    tail: vec3(-0.17, 0.88, 0),
    limits: joint(
      limit(-5, 150, 'Flexion', 'Extension'),
      limit(-85, 85, 'Supination', 'Pronation'),
      null,
    ),
    radius: 0.042,
  },
  {
    name: 'hand_l',
    parent: 'forearm_l',
    head: vec3(-0.17, 0.88, 0),
    tail: vec3(-0.17, 0.79, 0),
    limits: joint(
      limit(-30, 20, 'Radial deviation', 'Ulnar deviation'),
      null,
      limit(-70, 80, 'Flexion', 'Extension'),
    ),
    radius: 0.035,
  },
  {
    name: 'thigh_l',
    parent: 'pelvis',
    head: vec3(-0.09, 0.92, 0),
    tail: vec3(-0.082, 0.5, 0),
    limits: joint(
      limit(-25, 125, 'Flexion', 'Extension'),
      limit(-40, 50, 'External rotation', 'Internal rotation'),
      limit(-45, 25, 'Adduction', 'Abduction'),
    ),
    radius: 0.08,
  },
  {
    name: 'shin_l',
    parent: 'thigh_l',
    head: vec3(-0.082, 0.5, 0),
    tail: vec3(-0.082, 0.08, 0),
    limits: joint(
      limit(-150, 2, 'Extension', 'Flexion'),
      limit(-15, 15, 'External rotation', 'Internal rotation'),
      null,
    ),
    radius: 0.056,
  },
  {
    name: 'foot_l',
    parent: 'shin_l',
    head: vec3(-0.082, 0.08, 0),
    tail: vec3(-0.082, 0.025, 0.14),
    limits: joint(
      // Weight-bearing dorsiflexion reaches far past the passive range, and a
      // squat needs it: the shin has to travel forward over a planted foot.
      limit(-45, 35, 'Dorsiflexion', 'Plantarflexion'),
      limit(-15, 25, 'Inversion', 'Eversion'),
      limit(-10, 10, 'Adduction', 'Abduction'),
    ),
    radius: 0.04,
  },
  {
    name: 'toe_l',
    parent: 'foot_l',
    head: vec3(-0.082, 0.025, 0.14),
    tail: vec3(-0.082, 0.02, 0.21),
    limits: joint(limit(-35, 60, 'Extension', 'Flexion'), null, null),
    radius: 0.028,
  },
];

// ---------------------------------------------------------------------------
// Fingers — generated, because 30 near-identical bones are not worth typing out
// ---------------------------------------------------------------------------

interface FingerSpec {
  finger: Finger;
  /** Knuckle position on the left hand, world space at rest. */
  knuckle: Vec3;
  /** Direction the finger points at rest (need not be normalised). */
  direction: Vec3;
  /** Length of each of the three segments, in metres. */
  segments: [number, number, number];
  radius: number;
}

/**
 * At rest the arms hang with the palms facing the thighs, so the fingers spread
 * along Z: the index finger sits towards the front of the body, the little
 * finger towards the back.
 */
const FINGER_SPECS: FingerSpec[] = [
  {
    finger: 'thumb',
    knuckle: vec3(-0.163, 0.852, 0.022),
    direction: vec3(0.06, -0.72, 0.69),
    segments: [0.042, 0.032, 0.024],
    radius: 0.011,
  },
  {
    finger: 'index',
    knuckle: vec3(-0.171, 0.789, 0.032),
    direction: vec3(-0.01, -1, 0.02),
    segments: [0.042, 0.026, 0.02],
    radius: 0.0095,
  },
  {
    finger: 'middle',
    knuckle: vec3(-0.172, 0.788, 0.011),
    direction: vec3(0, -1, 0),
    segments: [0.046, 0.028, 0.021],
    radius: 0.0095,
  },
  {
    finger: 'ring',
    knuckle: vec3(-0.171, 0.789, -0.01),
    direction: vec3(0.005, -1, -0.015),
    segments: [0.042, 0.026, 0.02],
    radius: 0.009,
  },
  {
    finger: 'pinky',
    knuckle: vec3(-0.168, 0.792, -0.03),
    direction: vec3(0.01, -1, -0.03),
    segments: [0.034, 0.021, 0.017],
    radius: 0.008,
  },
];

/**
 * Finger flexion curls towards the palm, which at rest faces the body. In the
 * bone frame convention that puts flexion on the z axis, not x — the same as
 * the wrist.
 */
function fingerLimits(segment: number, finger: Finger): JointLimits {
  const isBase = segment === 0;
  const flexion =
    finger === 'thumb'
      ? [-25, 60]
      : segment === 0
        ? [-30, 90]
        : segment === 1
          ? [-5, 110]
          : [-5, 80];
  return joint(
    isBase ? limit(-14, 14, 'Spread towards thumb', 'Spread towards little finger') : null,
    null,
    limit(flexion[0], flexion[1], 'Flexion', 'Extension'),
  );
}

function buildFingerBones(): BoneDefinition[] {
  const bones: BoneDefinition[] = [];
  for (const spec of FINGER_SPECS) {
    const length = Math.hypot(spec.direction.x, spec.direction.y, spec.direction.z);
    const unit = vec3(
      spec.direction.x / length,
      spec.direction.y / length,
      spec.direction.z / length,
    );
    let head = spec.knuckle;
    spec.segments.forEach((segmentLength, index) => {
      const tail = vec3(
        head.x + unit.x * segmentLength,
        head.y + unit.y * segmentLength,
        head.z + unit.z * segmentLength,
      );
      bones.push({
        name: `${spec.finger}_0${index + 1}_l` as BoneName,
        parent: (index === 0
          ? 'hand_l'
          : `${spec.finger}_0${index}_l`) as BoneName,
        head,
        tail,
        limits: fingerLimits(index, spec.finger),
        radius: spec.radius * (1 - index * 0.12),
        minor: true,
      });
      head = tail;
    });
  }
  return bones;
}

/**
 * Stage 2 shoulder widening, metres outboard per side.
 *
 * The canonical rig was narrower across the shoulders than the supplied
 * physique reference by 4.17% of figure height. Half of that per side, at
 * RIG_HEIGHT (1.75, declared below this point), is this. The character's own
 * arm chain is translated by the same fraction of its own height, so the two
 * stay in step — a grip or a contact solved on one is solved on the other.
 *
 * The whole arm translates; nothing is scaled. Upper-arm and forearm lengths
 * are untouched, and the clavicle simply spans further, which is what a wider
 * shoulder is. No mass is added: widening by inflating the deltoid was
 * considered and rejected.
 */
export const SHOULDER_WIDENING = 0.01924 * 1.75;

/** The chain that moves: everything outboard of the sternoclavicular joint. */
const widened = (bones: BoneDefinition[]): BoneDefinition[] =>
  bones.map((bone) => {
    if (bone.name === 'clavicle_l') {
      // Its head stays at the sternum; only the tail follows the arm.
      return { ...bone, tail: vec3(bone.tail.x - SHOULDER_WIDENING, bone.tail.y, bone.tail.z) };
    }
    if (!/^(upperarm|forearm|hand|thumb|index|middle|ring|pinky)/.test(bone.name)) return bone;
    return {
      ...bone,
      head: vec3(bone.head.x - SHOULDER_WIDENING, bone.head.y, bone.head.z),
      tail: vec3(bone.tail.x - SHOULDER_WIDENING, bone.tail.y, bone.tail.z),
    };
  });

const LEFT_ALL = widened([...LEFT_BONES, ...buildFingerBones()]);

/** Every bone of the canonical rig, parents always before their children. */
export const HUMANOID_BONES: BoneDefinition[] = [
  ...CENTRE_BONES,
  ...LEFT_ALL,
  ...LEFT_ALL.map(mirrorBone),
];

/** Approximate standing height of the rest pose, in metres. */
export const RIG_HEIGHT = 1.75;

export const SIDE_LIST: readonly Side[] = SIDES;
export const FINGER_LIST: readonly Finger[] = FINGERS;
