"""Build human-reviewable summaries of every O4 candidate with full 15-pose evidence.

python scripts/build_original_v1_candidate_review.py

Reads ORIGINAL_V1_WORK/candidates/repair_checks/full_<rN>_* (produced by
RUN_ORIGINAL_V1_FULL_EVIDENCE.bat) plus the pinned R2 report and the candidate
manifests, and writes ORIGINAL_V1_WORK/candidates/review/:
  candidate_review.md        - concise per-candidate table and key before/after metrics
  candidate_metrics.csv      - per candidate x pose x region min/max, volume, p01/p99, self-intersections
  candidate_summary.json     - failures, regressions, queue status, hashes
Read-only: never changes candidates, thresholds or baselines.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAND = ROOT / "ORIGINAL_V1_WORK" / "candidates"
RC = CAND / "repair_checks"
OUT = CAND / "review"
KEY_REGIONS = ("shoulder", "torso", "arm", "hand", "finger", "thumb")


def load(p):
    return json.loads(Path(p).read_text(encoding="utf-8"))


def main():
    OUT.mkdir(exist_ok=True)
    r2 = {x["pose"]: x for x in load(CAND / "pose_test_report_r2.json")}
    revs = sorted({m.group(1) for f in RC.glob("full_*_merged_pose_report.json")
                   if (m := re.match(r"full_(r\d+)_merged_pose_report\.json", f.name))}, key=lambda r: int(r[1:]))
    rows, summary = [], {}
    for pose, x in r2.items():
        for rg, st in x["by_region"].items():
            rows.append(["R2", pose, rg, st["min_ratio"], st["max_ratio"], x["volume_ratio"], x["edge_ratio_p01"],
                         x["edge_ratio_p99"], x["self_intersecting_face_pairs"]])
    for rev in revs:
        rep = {x["pose"]: x for x in load(RC / f"full_{rev}_merged_pose_report.json")}
        comp = load(RC / f"full_{rev}_comparison_vs_R2.json")
        queue = (RC / f"full_{rev}_repair_queue.md").read_text(encoding="utf-8")
        pri = dict(re.findall(r"## Priority (\d) — (\w+)", queue))
        man = CAND / f"HomeGymPT_Male_ORIGINAL_v1_O4_CANDIDATE_{rev}.json"
        sha = load(man)["candidate_sha256"] if man.exists() else None
        summary[rev] = {"failed_checks": comp["candidate_failed_checks"], "regressions_vs_R2": comp["regression_count"],
                        "improvements_vs_R2": comp["improvement_count"], "priorities": pri, "candidate_sha256": sha,
                        "regressions": [f"{r['name']}{'/' + r['region'] if r.get('region') else ''}: {r['metric']} "
                                        f"{r['baseline']} -> {r['candidate']}" for r in comp["regressions"]],
                        "poses": len(rep)}
        for pose, x in rep.items():
            for rg, st in x["by_region"].items():
                rows.append([rev, pose, rg, st["min_ratio"], st["max_ratio"], x["volume_ratio"], x["edge_ratio_p01"],
                             x["edge_ratio_p99"], x["self_intersecting_face_pairs"]])
    with (OUT / "candidate_metrics.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["candidate", "pose", "region", "min_ratio", "max_ratio", "volume_ratio", "edge_ratio_p01",
                    "edge_ratio_p99", "self_intersecting_face_pairs"])
        w.writerows(rows)
    (OUT / "candidate_summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    lines = ["# ORIGINAL v1 O4 candidate review (generated)", "",
             "Generated by `scripts/build_original_v1_candidate_review.py` from committed full-evidence reports.",
             "Development-blocker profile; R2 = pinned baseline (54 failed checks). **No candidate is accepted; "
             "production approval is false.**", "",
             "| Candidate | Poses | Failed | Regressions vs R2 | Improvements vs R2 | P1 | P2 | P3 | SHA-256 |",
             "|---|---:|---:|---:|---:|---|---|---|---|"]
    for rev, s in summary.items():
        p = s["priorities"]
        lines.append(f"| {rev} | {s['poses']} | {s['failed_checks']} | {s['regressions_vs_R2']} | "
                     f"{s['improvements_vs_R2']} | {p.get('1', '?')} | {p.get('2', '?')} | {p.get('3', '?')} | "
                     f"`{(s['candidate_sha256'] or '-')[:16]}` |")
    lines += ["", "## Key worst-case metrics per candidate (min over poses of region min, max of region max)", "",
              "| Candidate | " + " | ".join(f"{r} min / max" for r in KEY_REGIONS) + " | max self-int. |",
              "|---|" + "---|" * (len(KEY_REGIONS) + 1)]
    by = {}
    for c, pose, rg, mn, mx, *_rest, si in rows:
        e = by.setdefault(c, {})
        a = e.setdefault(rg, [9.0, 0.0])
        a[0], a[1] = min(a[0], mn), max(a[1], mx)
        e["si"] = max(e.get("si", 0), si)
    for c in ["R2", *revs]:
        e = by[c]
        cells = [f"{e[r][0]:.3f} / {e[r][1]:.2f}" if r in e else "-" for r in KEY_REGIONS]
        lines.append(f"| {c} | " + " | ".join(cells) + f" | {e['si']:.0f} |")
    lines += ["", "## Regressions vs R2 (strict comparator)", ""]
    for rev, s in summary.items():
        lines.append(f"- **{rev}** ({s['regressions_vs_R2']}): " + ("; ".join(s["regressions"]) or "none"))
    (OUT / "candidate_review.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("REVIEW", OUT, "candidates:", ", ".join(revs))


if __name__ == "__main__":
    main()
