import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function extensionReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'extension_phase_order',
      label: 'Extension follows lower, stretch, extend, lockout',
      order: ['eccentric', 'stretch', 'concentric', 'lockout'],
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_lockout',
      label: 'Elbow reaches near lockout',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['lockout'],
      envelope: { min: 0, max: 18 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_stretch',
      label: 'Elbow reaches a deep stretch behind the head',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['stretch'],
      envelope: { min: 100, max: 135 },
    },
    {
      kind: 'jointExcursion',
      id: 'extension_elbow_rom',
      label: 'Elbow uses a full extension range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 85, max: 135 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'extension_upper_arm_vertical',
      label: 'Upper arm stays close to vertical',
      bone: 'upperarm_l',
      worldAxis: 'y',
      envelope: { min: 0, max: 25 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'extension_torso_upright',
      label: 'Torso stays upright',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: 10 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_grip',
      label: 'Forearm keeps a neutral grip',
      bone: 'forearm_l',
      axis: 'y',
      envelope: { min: -15, max: 20 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_wrist',
      label: 'Wrist stays neutral',
      bone: 'hand_l',
      axis: 'z',
      envelope: { min: -15, max: 18 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'extension_elbow_symmetry',
      label: 'Both elbows flex and extend together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 0.75,
    },
    {
      kind: 'landmarkStationary',
      id: 'extension_left_foot_still',
      label: 'Left foot stays planted',
      bone: 'foot_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkStationary',
      id: 'extension_right_foot_still',
      label: 'Right foot stays planted',
      bone: 'foot_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'extension_hand_lowers',
      label: 'Hand lowers behind the head without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.02,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'extension_hand_rises',
      label: 'Hand rises to lockout without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.02,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'extension.dumbbell_overhead.v1',
    referenceVersion: 1,
    family: 'extension',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'standing' },
    provenance:
      'HOME GYM PT internal overhead-triceps-extension reference draft. Independent review required before certification.',
    reviewViews: [
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'upper_body' },
      { id: 'hands', label: 'Hands and dumbbells', preset: 'focus', target: 'hands' },
    ],
    checks,
  };
}
