import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function extensionReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const pushdown = exercise.equipment.required.includes('cable_tower');
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'extension_phase_order',
      label: 'Extension follows eccentric, stretch, concentric, lockout',
      order: ['eccentric', 'stretch', 'concentric', 'lockout'],
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_lockout',
      label: 'Elbow reaches near-full extension',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['lockout'],
      envelope: { min: 0, max: 20 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_stretch',
      label: 'Elbow reaches a full stretched position',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['stretch'],
      envelope: { min: 90, max: 135 },
    },
    {
      kind: 'jointExcursion',
      id: 'extension_elbow_rom',
      label: 'Elbow uses a substantial extension range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 75, max: 135 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'extension_upper_arm_position',
      label: pushdown ? 'Upper arm stays close to vertical at the side' : 'Upper arm stays pointing overhead',
      bone: 'upperarm_l',
      worldAxis: 'y',
      envelope: { min: 0, max: pushdown ? 25 : 22 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_grip',
      label: pushdown ? 'Pushdown holds a pronated bar grip' : 'Overhead extension holds a neutral grip',
      bone: 'forearm_l',
      axis: 'y',
      envelope: pushdown ? { min: -90, max: -60 } : { min: -15, max: 20 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_wrist_neutral',
      label: 'Wrist stays neutral',
      bone: 'hand_l',
      axis: 'z',
      envelope: { min: -15, max: 18 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'extension_torso',
      label: pushdown ? 'Torso keeps only a modest cable-stack lean' : 'Torso remains upright',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: pushdown ? 25 : 12 },
    },
    {
      kind: 'jointEnvelope',
      id: 'extension_spine_neutral',
      label: 'Lower back remains neutral',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 12 },
    },
    {
      kind: 'rootEnvelope',
      id: 'extension_root_pitch',
      label: pushdown ? 'Pushdown keeps its slight whole-body lean' : 'Overhead extension remains upright',
      axis: 'x',
      envelope: pushdown ? { min: 5, max: 20 } : { min: -5, max: 5 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'extension_elbow_symmetry',
      label: 'Both elbows move together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 0.5,
    },
    {
      kind: 'landmarkStationary',
      id: 'extension_left_foot_still',
      label: 'Left foot stays planted',
      bone: 'foot_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.012,
    },
    {
      kind: 'landmarkStationary',
      id: 'extension_right_foot_still',
      label: 'Right foot stays planted',
      bone: 'foot_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.012,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'extension_eccentric_path',
      label: pushdown ? 'Bar rises smoothly during the eccentric' : 'Dumbbells lower smoothly behind the head',
      bone: 'hand_l',
      axis: 'y',
      phase: 'eccentric',
      direction: pushdown ? 'increasing' : 'decreasing',
      tolerance: 0.02,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'extension_concentric_path',
      label: pushdown ? 'Bar travels down smoothly to lockout' : 'Dumbbells rise smoothly to lockout',
      bone: 'hand_l',
      axis: 'y',
      phase: 'concentric',
      direction: pushdown ? 'decreasing' : 'increasing',
      tolerance: 0.02,
    },
  ];

  return {
    schemaVersion: 1,
    id: pushdown ? 'extension.cable_pushdown.v1' : 'extension.overhead_dumbbell.v1',
    referenceVersion: 1,
    family: 'extension',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'standing' },
    provenance:
      'HOME GYM PT internal triceps-extension reference draft. The envelope is independent of extensionFamily() at runtime and requires review before certification.',
    reviewViews: [
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'upper_body' },
      { id: 'hands', label: 'Hands and implement', preset: 'focus', target: 'hands' },
    ],
    checks,
  };
}
