import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function hingeReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'hinge_phase_order',
      label: 'Hinge follows lower, stretch, stand, top',
      order: ['eccentric', 'bottom', 'concentric', 'top'],
    },
    {
      kind: 'rootEnvelope',
      id: 'hinge_root_pitch',
      label: 'Body pitches deeply from the hips',
      axis: 'x',
      phases: ['bottom'],
      envelope: { min: 50, max: 90 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'hinge_torso_angle',
      label: 'Torso reaches a deep hinge',
      bone: 'spine_02',
      worldAxis: 'y',
      phases: ['bottom'],
      envelope: { min: 50, max: 90 },
    },
    {
      kind: 'jointEnvelope',
      id: 'hinge_lumbar_neutral',
      label: 'Lower back stays neutral',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 10 },
    },
    {
      kind: 'jointEnvelope',
      id: 'hinge_upper_back_neutral',
      label: 'Upper back stays flat',
      bone: 'spine_03',
      axis: 'x',
      envelope: { min: -6, max: 10 },
    },
    {
      kind: 'jointEnvelope',
      id: 'hinge_soft_knee',
      label: 'Knee remains soft without becoming a squat',
      bone: 'shin_l',
      axis: 'x',
      envelope: { min: -35, max: 2 },
    },
    {
      kind: 'jointEnvelope',
      id: 'hinge_arms_long',
      label: 'Arms remain long',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: -5, max: 18 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'hinge_hips_back',
      label: 'Hips travel behind the feet at the bottom',
      point: 'pelvis',
      relativeTo: 'foot_l',
      axis: 'z',
      phases: ['bottom'],
      normalizeBy: 'standingHeight',
      envelope: { min: -0.2, max: -0.04 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'hinge_hips_high',
      label: 'Hips stay well above the knees',
      point: 'pelvis',
      relativeTo: 'shin_l',
      axis: 'y',
      normalizeBy: 'standingHeight',
      envelope: { min: 0.12, max: 0.5 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'hinge_hand_path',
      label: 'Dumbbell remains close to the leg line',
      point: 'hand_l',
      relativeTo: 'foot_l',
      axis: 'z',
      normalizeBy: 'standingHeight',
      envelope: { min: -0.05, max: 0.18 },
    },
    {
      kind: 'landmarkStationary',
      id: 'hinge_left_foot_still',
      label: 'Left foot remains planted',
      bone: 'foot_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkStationary',
      id: 'hinge_right_foot_still',
      label: 'Right foot remains planted',
      bone: 'foot_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'hinge_knee_symmetry',
      label: 'Both knees remain matched',
      left: 'shin_l',
      right: 'shin_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'hinge.dumbbell_rdl.v1',
    referenceVersion: 1,
    family: 'hinge',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'standing' },
    provenance:
      'HOME GYM PT internal Romanian-deadlift reference draft. Independent review required; it is not populated from hingeFamily() at runtime.',
    reviewViews: [
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'full_body' },
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'hands', label: 'Dumbbell path', preset: 'focus', target: 'hands' },
    ],
    checks,
  };
}
