import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function horizontalPressReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'pushup_phase_order',
      label: 'Push-up follows lower, bottom, press, top',
      order: ['eccentric', 'bottom', 'concentric', 'top'],
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_top_elbow',
      label: 'Elbow is near extension at the top',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['top'],
      envelope: { min: 0, max: 30 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_bottom_elbow',
      label: 'Elbow bends strongly at the bottom',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['bottom'],
      envelope: { min: 70, max: 110 },
    },
    {
      kind: 'jointExcursion',
      id: 'pushup_elbow_rom',
      label: 'Elbow uses a full push-up range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 50, max: 100 },
    },
    {
      kind: 'rootEnvelope',
      id: 'pushup_body_pitch',
      label: 'Body remains in the prone push-up orientation',
      axis: 'x',
      envelope: { min: 68, max: 92 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_no_sag',
      label: 'Lower back remains braced',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 6 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_trunk_rigid',
      label: 'Torso remains rigid',
      bone: 'spine_02',
      axis: 'x',
      envelope: { min: -6, max: 6 },
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_left_hand_still',
      label: 'Left hand stays planted',
      bone: 'hand_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.008,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_right_hand_still',
      label: 'Right hand stays planted',
      bone: 'hand_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.008,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_left_toe_still',
      label: 'Left toe contact stays planted',
      bone: 'toe_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_right_toe_still',
      label: 'Right toe contact stays planted',
      bone: 'toe_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkDistanceEnvelope',
      id: 'pushup_hand_width',
      label: 'Hands stay shoulder-width or slightly wider',
      from: 'hand_l',
      to: 'hand_r',
      axis: 'x',
      normalizeBy: 'shoulderWidth',
      envelope: { min: 1.2, max: 1.9 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'pushup_elbow_flare',
      label: 'Elbow stays out from the torso without flaring to ninety degrees',
      point: 'forearm_l',
      relativeTo: 'upperarm_l',
      axis: 'x',
      normalizeBy: 'shoulderWidth',
      envelope: { min: -0.8, max: -0.1 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'pushup_elbow_tracks_back',
      label: 'Elbow tracks back toward the feet',
      point: 'forearm_l',
      relativeTo: 'upperarm_l',
      axis: 'z',
      normalizeBy: 'standingHeight',
      envelope: { min: -0.22, max: -0.01 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'pushup_elbow_symmetry',
      label: 'Both elbows bend together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pushup_body_lowers',
      label: 'Pelvis lowers continuously through the eccentric',
      bone: 'pelvis',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pushup_body_rises',
      label: 'Pelvis rises continuously through the press',
      bone: 'pelvis',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.01,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'horizontal_press.standard_pushup.v1',
    referenceVersion: 1,
    family: 'horizontal_press',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'floor' },
    provenance:
      'HOME GYM PT internal standard-push-up reference draft. Independent review required before it may gate approval or drive correction.',
    reviewViews: [
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'full_body' },
      { id: 'hands', label: 'Hands and elbows', preset: 'focus', target: 'hands' },
      { id: 'feet', label: 'Toe contacts', preset: 'focus', target: 'feet' },
    ],
    checks,
  };
}
