import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function horizontalPressReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'pushup_phase_order',
      label: 'Push-up follows lower, bottom, press, top',
      order: ['eccentric', 'bottom', 'concentric', 'top'],
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_top_elbow',
      label: 'Elbow is close to straight at the top',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['top'],
      envelope: { min: 0, max: 30 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_bottom_elbow',
      label: 'Elbow reaches a deep press position',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['bottom'],
      envelope: { min: 70, max: 115 },
    },
    {
      kind: 'jointExcursion',
      id: 'pushup_elbow_rom',
      label: 'Elbow uses a substantial pressing range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 55, max: 105 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_spine_rigid',
      label: 'Mid spine stays rigid',
      bone: 'spine_02',
      axis: 'x',
      envelope: { min: -7, max: 7 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pushup_hips_rigid',
      label: 'Lower spine does not sag or pike',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -7, max: 7 },
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_left_hand_fixed',
      label: 'Left hand remains planted',
      bone: 'hand_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.012,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_right_hand_fixed',
      label: 'Right hand remains planted',
      bone: 'hand_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.012,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_left_toe_fixed',
      label: 'Left toe remains planted',
      bone: 'toe_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.015,
    },
    {
      kind: 'landmarkStationary',
      id: 'pushup_right_toe_fixed',
      label: 'Right toe remains planted',
      bone: 'toe_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.015,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'pushup_elbow_symmetry',
      label: 'Both elbows bend together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pushup_chest_lowers',
      label: 'Chest lowers without reversing',
      bone: 'spine_03',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pushup_chest_rises',
      label: 'Chest rises without reversing',
      bone: 'spine_03',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.01,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'horizontal_press.standard_pushup.v1',
    referenceVersion: 1,
    family: 'horizontal_press',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'floor' },
    provenance:
      'HOME GYM PT internal standard-push-up reference draft. Independent review required before certification.',
    reviewViews: [
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'full_body' },
      { id: 'hands', label: 'Hands and shoulders', preset: 'focus', target: 'shoulders' },
    ],
    checks,
  };
}
