import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function overheadPressReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const seated = exercise.equipment.required.includes('flat_bench');
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'press_phase_order',
      label: 'Press follows lift, lockout, lower, rack',
      order: ['concentric', 'lockout', 'eccentric', 'racked'],
    },
    {
      kind: 'jointEnvelope',
      id: 'elbow_rack',
      label: 'Elbow is deeply flexed in the rack',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['racked'],
      envelope: { min: 80, max: 120 },
    },
    {
      kind: 'jointEnvelope',
      id: 'elbow_lockout',
      label: 'Elbow reaches overhead extension',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['lockout'],
      envelope: { min: 0, max: 20 },
    },
    {
      kind: 'jointExcursion',
      id: 'elbow_rom',
      label: 'Elbow uses a full pressing range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 75, max: 120 },
    },
    {
      kind: 'jointEnvelope',
      id: 'arm_elevation',
      label: 'Upper arm travels from rack to overhead',
      bone: 'upperarm_l',
      axis: 'z',
      envelope: { min: -178, max: -55 },
    },
    {
      kind: 'jointExcursion',
      id: 'arm_elevation_rom',
      label: 'Shoulder elevation excursion is substantial',
      bone: 'upperarm_l',
      axis: 'z',
      envelope: { min: 75, max: 125 },
    },
    {
      kind: 'jointEnvelope',
      id: 'lumbar_brace',
      label: 'Lower back stays braced',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 12 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'torso_upright',
      label: 'Torso remains upright',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: 12 },
    },
    {
      kind: 'jointEnvelope',
      id: 'wrist_neutral',
      label: 'Wrist stays neutral under the dumbbell',
      bone: 'hand_l',
      axis: 'z',
      envelope: { min: -15, max: 15 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'lockout_height',
      label: 'Hand finishes well above the shoulder',
      point: 'hand_l',
      relativeTo: 'upperarm_l',
      axis: 'y',
      phases: ['lockout'],
      normalizeBy: 'armLength',
      envelope: { min: 0.65, max: 1.35 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'press_elbow_symmetry',
      label: 'Both elbows extend together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 0.5,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'press_arm_symmetry',
      label: 'Both upper arms elevate together',
      left: 'upperarm_l',
      right: 'upperarm_r',
      axis: 'z',
      toleranceDeg: 0.5,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'hand_rises',
      label: 'Dumbbell rises through the press without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.02,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'hand_lowers',
      label: 'Dumbbell lowers through the eccentric without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.02,
    },
  ];

  return {
    schemaVersion: 1,
    id: `overhead_press.${seated ? 'seated' : 'standing'}.pronated.v1`,
    referenceVersion: 1,
    family: 'overhead_press',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: seated ? 'seated' : 'standing' },
    provenance:
      'HOME GYM PT internal overhead-press reference draft. Independent review required before certification; runtime values are not read from pressFamily().',
    reviewViews: [
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'upper_body' },
      { id: 'shoulders', label: 'Shoulder close-up', preset: 'focus', target: 'shoulders' },
    ],
    checks,
  };
}
