import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function raiseReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const front = /front_raise/.test(exercise.id) || /front_raise/.test(exercise.clipName);
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'raise_phase_order',
      label: 'Raise follows lift, top, lower, reset',
      order: ['concentric', 'top', 'eccentric', 'bottom'],
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'raise_top_height',
      label: 'Upper arm reaches around shoulder height',
      bone: 'upperarm_l',
      worldAxis: 'y',
      phases: ['top'],
      envelope: { min: 68, max: 100 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'raise_not_too_high',
      label: 'Hand stops around shoulder height rather than continuing overhead',
      point: 'hand_l',
      relativeTo: 'upperarm_l',
      axis: 'y',
      phases: ['top'],
      normalizeBy: 'armLength',
      envelope: { min: -0.18, max: 0.12 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_soft_elbow',
      label: 'Elbow stays softly bent',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 5, max: 30 },
    },
    {
      kind: 'jointExcursion',
      id: 'raise_elbow_quiet',
      label: 'Elbow angle stays nearly fixed through the raise',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 0, max: 8 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_plane',
      label: front ? 'Front raise stays in front of the body' : 'Lateral raise stays in the scapular plane',
      bone: 'upperarm_l',
      axis: front ? 'z' : 'x',
      envelope: front ? { min: -22, max: 8 } : { min: 0, max: 38 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_grip',
      label: front ? 'Front raise keeps the forearm pronated' : 'Lateral raise keeps a neutral forearm',
      bone: 'forearm_l',
      axis: 'y',
      envelope: front ? { min: -85, max: -55 } : { min: -15, max: 20 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_no_shrug',
      label: 'Clavicle stays quiet rather than shrugging the weight',
      bone: 'clavicle_l',
      axis: 'z',
      envelope: { min: -8, max: 8 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'raise_torso_upright',
      label: 'Torso stays upright',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: 12 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_spine_neutral',
      label: 'Lower back does not lean to swing the weights',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 10 },
    },
    {
      kind: 'jointEnvelope',
      id: 'raise_wrist_neutral',
      label: 'Wrist stays neutral',
      bone: 'hand_l',
      axis: 'z',
      envelope: { min: -15, max: 18 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'raise_arm_symmetry',
      label: 'Both upper arms rise together',
      left: 'upperarm_l',
      right: 'upperarm_r',
      axis: front ? 'x' : 'z',
      toleranceDeg: 0.75,
    },
    {
      kind: 'landmarkStationary',
      id: 'raise_left_foot_still',
      label: 'Left foot stays planted',
      bone: 'foot_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkStationary',
      id: 'raise_right_foot_still',
      label: 'Right foot stays planted',
      bone: 'foot_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'raise_hand_rises',
      label: 'Dumbbell rises without a mid-lift reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.015,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'raise_hand_lowers',
      label: 'Dumbbell lowers without a mid-lowering reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.015,
    },
  ];

  return {
    schemaVersion: 1,
    id: front ? 'raise.dumbbell_front.v1' : 'raise.dumbbell_lateral.v1',
    referenceVersion: 1,
    family: 'raise',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'standing' },
    provenance:
      'HOME GYM PT internal shoulder-raise reference draft. It is independent of raiseFamily() at runtime and must be reviewed before certification.',
    reviewViews: [
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'upper_body' },
      { id: 'shoulders', label: 'Shoulder close-up', preset: 'focus', target: 'shoulders' },
    ],
    checks,
  };
}
