import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function rowReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'row_phase_order',
      label: 'Row follows pull, squeeze, lower, stretch',
      order: ['concentric', 'squeeze', 'eccentric', 'stretch'],
    },
    {
      kind: 'rootEnvelope',
      id: 'row_hinge_pitch',
      label: 'Bent-over posture remains established',
      axis: 'x',
      envelope: { min: 40, max: 60 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'row_torso_angle',
      label: 'Torso stays well bent forward',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 35, max: 70 },
    },
    {
      kind: 'landmarkStationary',
      id: 'row_torso_still',
      label: 'Upper torso stays still while the arms row',
      bone: 'spine_03',
      normalizeBy: 'standingHeight',
      tolerance: 0.02,
    },
    {
      kind: 'jointEnvelope',
      id: 'row_lumbar_neutral',
      label: 'Lower back stays neutral',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 10 },
    },
    {
      kind: 'jointEnvelope',
      id: 'row_elbow_back',
      label: 'Upper arm reaches behind the torso at squeeze',
      bone: 'upperarm_l',
      axis: 'x',
      phases: ['squeeze'],
      envelope: { min: -45, max: -15 },
    },
    {
      kind: 'jointEnvelope',
      id: 'row_elbow_flexion',
      label: 'Elbow bends strongly at squeeze',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['squeeze'],
      envelope: { min: 65, max: 105 },
    },
    {
      kind: 'jointEnvelope',
      id: 'row_elbow_tucked',
      label: 'Upper arm remains close to the ribs',
      bone: 'upperarm_l',
      axis: 'z',
      envelope: { min: -32, max: -2 },
    },
    {
      kind: 'jointEnvelope',
      id: 'row_neutral_grip',
      label: 'Forearm stays near neutral rotation',
      bone: 'forearm_l',
      axis: 'y',
      envelope: { min: -15, max: 20 },
    },
    {
      kind: 'jointEnvelope',
      id: 'row_wrist_neutral',
      label: 'Wrist stays neutral',
      bone: 'hand_l',
      axis: 'z',
      envelope: { min: -15, max: 18 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'row_arm_symmetry',
      label: 'Both upper arms pull together',
      left: 'upperarm_l',
      right: 'upperarm_r',
      axis: 'x',
      toleranceDeg: 0.5,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'row_elbow_symmetry',
      label: 'Both elbows bend together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 0.5,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'row_hand_rises',
      label: 'Dumbbell rises through the pull without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.02,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'row_hand_lowers',
      label: 'Dumbbell lowers through the eccentric without reversal',
      bone: 'hand_l',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.02,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'row.dumbbell_bent_over.v1',
    referenceVersion: 1,
    family: 'row',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'standing' },
    provenance:
      'HOME GYM PT internal bent-over-row reference draft. Independent review required before any gating or correction.',
    reviewViews: [
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'upper_body' },
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'hands', label: 'Grip and dumbbells', preset: 'focus', target: 'hands' },
    ],
    checks,
  };
}
