import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function squatReferenceFor(_exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'squat_phase_order',
      label: 'Squat follows descend, bottom, stand, top',
      order: ['eccentric', 'bottom', 'concentric', 'top'],
    },
    {
      kind: 'rootPositionEnvelope',
      id: 'squat_depth_root',
      label: 'Body reaches a substantial squat depth',
      axis: 'y',
      phases: ['bottom'],
      normalizeBy: 'standingHeight',
      envelope: { min: -0.35, max: -0.15 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'squat_torso',
      label: 'Torso leans but does not fold excessively',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: 55 },
    },
    {
      kind: 'jointEnvelope',
      id: 'squat_spine_neutral',
      label: 'Lower back remains near neutral',
      bone: 'spine_01',
      axis: 'x',
      envelope: { min: -6, max: 18 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'squat_hip_depth',
      label: 'Pelvis reaches around knee height',
      point: 'pelvis',
      relativeTo: 'shin_l',
      axis: 'y',
      phases: ['bottom'],
      normalizeBy: 'standingHeight',
      envelope: { min: -0.08, max: 0.08 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'squat_knee_track',
      label: 'Knee remains near the line of the foot',
      point: 'shin_l',
      relativeTo: 'foot_l',
      axis: 'x',
      normalizeBy: 'shoulderWidth',
      envelope: { min: -0.2, max: 0.28 },
    },
    {
      kind: 'landmarkStationary',
      id: 'squat_left_foot_still',
      label: 'Left foot stays planted',
      bone: 'foot_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkStationary',
      id: 'squat_right_foot_still',
      label: 'Right foot stays planted',
      bone: 'foot_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.01,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'squat_thigh_symmetry',
      label: 'Both hips flex together',
      left: 'thigh_l',
      right: 'thigh_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
    {
      kind: 'bilateralSymmetry',
      id: 'squat_knee_symmetry',
      label: 'Both knees flex together',
      left: 'shin_l',
      right: 'shin_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pelvis_descends',
      label: 'Pelvis descends continuously',
      bone: 'pelvis',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.01,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pelvis_rises',
      label: 'Pelvis rises continuously',
      bone: 'pelvis',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.01,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'squat.bodyweight.v1',
    referenceVersion: 1,
    family: 'squat',
    status: 'draft',
    applicability: { support: 'standing' },
    provenance:
      'HOME GYM PT internal bodyweight-squat reference draft. Independent biomechanical review required before certification.',
    reviewViews: [
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'full_body' },
      { id: 'feet', label: 'Feet and knees', preset: 'focus', target: 'feet' },
    ],
    checks,
  };
}
