import type { ExerciseDefinition } from '../../exercises/types';
import type { ReferenceCheckSpec, ReferenceSpec } from '../types';

export function verticalPullReferenceFor(exercise: ExerciseDefinition): ReferenceSpec {
  const checks: ReferenceCheckSpec[] = [
    {
      kind: 'phaseOrder',
      id: 'pullup_phase_order',
      label: 'Pull-up follows pull, top, lower, hang',
      order: ['concentric', 'top', 'eccentric', 'hang'],
    },
    {
      kind: 'jointEnvelope',
      id: 'pullup_dead_hang',
      label: 'Elbow reaches near extension in the dead hang',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['hang'],
      envelope: { min: 0, max: 25 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pullup_top_elbow',
      label: 'Elbow reaches strong flexion at the top',
      bone: 'forearm_l',
      axis: 'x',
      phases: ['top'],
      envelope: { min: 105, max: 150 },
    },
    {
      kind: 'jointExcursion',
      id: 'pullup_elbow_rom',
      label: 'Elbow uses a full vertical-pull range',
      bone: 'forearm_l',
      axis: 'x',
      envelope: { min: 90, max: 150 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pullup_shoulder_motion',
      label: 'Shoulder girdle rises in the hang and depresses at the top',
      bone: 'clavicle_l',
      axis: 'z',
      envelope: { min: -20, max: 15 },
    },
    {
      kind: 'segmentAngleEnvelope',
      id: 'pullup_trunk_line',
      label: 'Trunk stays near vertical',
      bone: 'spine_02',
      worldAxis: 'y',
      envelope: { min: 0, max: 20 },
    },
    {
      kind: 'landmarkStationary',
      id: 'pullup_left_hand_fixed',
      label: 'Left hand remains fixed on the bar',
      bone: 'hand_l',
      normalizeBy: 'standingHeight',
      tolerance: 0.008,
    },
    {
      kind: 'landmarkStationary',
      id: 'pullup_right_hand_fixed',
      label: 'Right hand remains fixed on the bar',
      bone: 'hand_r',
      normalizeBy: 'standingHeight',
      tolerance: 0.008,
    },
    {
      kind: 'landmarkDistanceEnvelope',
      id: 'pullup_grip_width',
      label: 'Grip remains just wider than the shoulders',
      from: 'hand_l',
      to: 'hand_r',
      axis: 'x',
      normalizeBy: 'shoulderWidth',
      envelope: { min: 1.1, max: 1.65 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'pullup_chin_height',
      label: 'Head/chin reaches bar height at the top',
      point: 'head',
      relativeTo: 'hand_l',
      axis: 'y',
      phases: ['top'],
      normalizeBy: 'standingHeight',
      envelope: { min: 0.02, max: 0.18 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'pullup_hang_depth',
      label: 'Shoulder hangs a full arm below the hand',
      point: 'upperarm_l',
      relativeTo: 'hand_l',
      axis: 'y',
      phases: ['hang'],
      normalizeBy: 'standingHeight',
      envelope: { min: -0.5, max: -0.24 },
    },
    {
      kind: 'relativeLandmarkEnvelope',
      id: 'pullup_no_kip',
      label: 'Pelvis stays behind the bar rather than swinging forward',
      point: 'pelvis',
      relativeTo: 'hand_l',
      axis: 'z',
      normalizeBy: 'standingHeight',
      envelope: { min: -0.2, max: 0.03 },
    },
    {
      kind: 'jointEnvelope',
      id: 'pullup_hips_quiet',
      label: 'Hip angle stays quiet',
      bone: 'thigh_l',
      axis: 'x',
      envelope: { min: -25, max: 10 },
    },
    {
      kind: 'bilateralSymmetry',
      id: 'pullup_elbow_symmetry',
      label: 'Both elbows pull together',
      left: 'forearm_l',
      right: 'forearm_r',
      axis: 'x',
      toleranceDeg: 1.0,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pullup_body_rises',
      label: 'Pelvis rises through the pull without reversal',
      bone: 'pelvis',
      axis: 'y',
      phase: 'concentric',
      direction: 'increasing',
      tolerance: 0.015,
    },
    {
      kind: 'landmarkMonotonic',
      id: 'pullup_body_lowers',
      label: 'Pelvis lowers through the eccentric without reversal',
      bone: 'pelvis',
      axis: 'y',
      phase: 'eccentric',
      direction: 'decreasing',
      tolerance: 0.015,
    },
  ];

  return {
    schemaVersion: 1,
    id: 'vertical_pull.strict_pullup.v1',
    referenceVersion: 1,
    family: 'vertical_pull',
    status: 'draft',
    applicability: { handOrientation: exercise.hands.orientation, support: 'hanging' },
    provenance:
      'HOME GYM PT internal strict-pull-up reference draft. Independent review required before it may gate approval or drive correction.',
    reviewViews: [
      { id: 'front', label: 'Front', preset: 'front', target: 'full_body' },
      { id: 'side', label: 'Side', preset: 'right', target: 'full_body' },
      { id: 'three_quarter', label: 'Three-quarter', preset: 'three_quarter', target: 'full_body' },
      { id: 'hands', label: 'Grip close-up', preset: 'focus', target: 'hands' },
    ],
    checks,
  };
}
